package model;

import java.util.Date;

public class Account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.id
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.uid
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.chuxu_zhaoshang
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    private Double chuxuZhaoshang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.chuxu_gongshang
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    private Double chuxuGongshang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.chuxu_jiaotong
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    private Double chuxuJiaotong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.xinyong_jiaotong
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    private Double xinyongJiaotong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.weixin_lingqian
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    private Double weixinLingqian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.weixin_licai
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    private Double weixinLicai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.alipay_yeb
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    private Double alipayYeb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.alipay_licai
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    private Double alipayLicai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.alipay2_yeb
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    private Double alipay2Yeb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.alipay2_licai
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    private Double alipay2Licai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.qq_qianbao
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    private Double qqQianbao;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.qq_licai
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    private Double qqLicai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.wallet
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    private Double wallet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.record_date
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    private Date recordDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.insert_date
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    private Date insertDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.last_update
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    private Date lastUpdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.note
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.id
     *
     * @return the value of t_account.id
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.id
     *
     * @param id the value for t_account.id
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.uid
     *
     * @return the value of t_account.uid
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.uid
     *
     * @param uid the value for t_account.uid
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.chuxu_zhaoshang
     *
     * @return the value of t_account.chuxu_zhaoshang
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    public Double getChuxuZhaoshang() {
        return chuxuZhaoshang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.chuxu_zhaoshang
     *
     * @param chuxuZhaoshang the value for t_account.chuxu_zhaoshang
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    public void setChuxuZhaoshang(Double chuxuZhaoshang) {
        this.chuxuZhaoshang = chuxuZhaoshang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.chuxu_gongshang
     *
     * @return the value of t_account.chuxu_gongshang
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    public Double getChuxuGongshang() {
        return chuxuGongshang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.chuxu_gongshang
     *
     * @param chuxuGongshang the value for t_account.chuxu_gongshang
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    public void setChuxuGongshang(Double chuxuGongshang) {
        this.chuxuGongshang = chuxuGongshang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.chuxu_jiaotong
     *
     * @return the value of t_account.chuxu_jiaotong
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    public Double getChuxuJiaotong() {
        return chuxuJiaotong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.chuxu_jiaotong
     *
     * @param chuxuJiaotong the value for t_account.chuxu_jiaotong
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    public void setChuxuJiaotong(Double chuxuJiaotong) {
        this.chuxuJiaotong = chuxuJiaotong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.xinyong_jiaotong
     *
     * @return the value of t_account.xinyong_jiaotong
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    public Double getXinyongJiaotong() {
        return xinyongJiaotong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.xinyong_jiaotong
     *
     * @param xinyongJiaotong the value for t_account.xinyong_jiaotong
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    public void setXinyongJiaotong(Double xinyongJiaotong) {
        this.xinyongJiaotong = xinyongJiaotong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.weixin_lingqian
     *
     * @return the value of t_account.weixin_lingqian
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    public Double getWeixinLingqian() {
        return weixinLingqian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.weixin_lingqian
     *
     * @param weixinLingqian the value for t_account.weixin_lingqian
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    public void setWeixinLingqian(Double weixinLingqian) {
        this.weixinLingqian = weixinLingqian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.weixin_licai
     *
     * @return the value of t_account.weixin_licai
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    public Double getWeixinLicai() {
        return weixinLicai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.weixin_licai
     *
     * @param weixinLicai the value for t_account.weixin_licai
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    public void setWeixinLicai(Double weixinLicai) {
        this.weixinLicai = weixinLicai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.alipay_yeb
     *
     * @return the value of t_account.alipay_yeb
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    public Double getAlipayYeb() {
        return alipayYeb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.alipay_yeb
     *
     * @param alipayYeb the value for t_account.alipay_yeb
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    public void setAlipayYeb(Double alipayYeb) {
        this.alipayYeb = alipayYeb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.alipay_licai
     *
     * @return the value of t_account.alipay_licai
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    public Double getAlipayLicai() {
        return alipayLicai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.alipay_licai
     *
     * @param alipayLicai the value for t_account.alipay_licai
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    public void setAlipayLicai(Double alipayLicai) {
        this.alipayLicai = alipayLicai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.alipay2_yeb
     *
     * @return the value of t_account.alipay2_yeb
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    public Double getAlipay2Yeb() {
        return alipay2Yeb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.alipay2_yeb
     *
     * @param alipay2Yeb the value for t_account.alipay2_yeb
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    public void setAlipay2Yeb(Double alipay2Yeb) {
        this.alipay2Yeb = alipay2Yeb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.alipay2_licai
     *
     * @return the value of t_account.alipay2_licai
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    public Double getAlipay2Licai() {
        return alipay2Licai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.alipay2_licai
     *
     * @param alipay2Licai the value for t_account.alipay2_licai
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    public void setAlipay2Licai(Double alipay2Licai) {
        this.alipay2Licai = alipay2Licai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.qq_qianbao
     *
     * @return the value of t_account.qq_qianbao
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    public Double getQqQianbao() {
        return qqQianbao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.qq_qianbao
     *
     * @param qqQianbao the value for t_account.qq_qianbao
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    public void setQqQianbao(Double qqQianbao) {
        this.qqQianbao = qqQianbao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.qq_licai
     *
     * @return the value of t_account.qq_licai
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    public Double getQqLicai() {
        return qqLicai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.qq_licai
     *
     * @param qqLicai the value for t_account.qq_licai
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    public void setQqLicai(Double qqLicai) {
        this.qqLicai = qqLicai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.wallet
     *
     * @return the value of t_account.wallet
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    public Double getWallet() {
        return wallet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.wallet
     *
     * @param wallet the value for t_account.wallet
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    public void setWallet(Double wallet) {
        this.wallet = wallet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.record_date
     *
     * @return the value of t_account.record_date
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    public Date getRecordDate() {
        return recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.record_date
     *
     * @param recordDate the value for t_account.record_date
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    public void setRecordDate(Date recordDate) {
        this.recordDate = recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.insert_date
     *
     * @return the value of t_account.insert_date
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    public Date getInsertDate() {
        return insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.insert_date
     *
     * @param insertDate the value for t_account.insert_date
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    public void setInsertDate(Date insertDate) {
        this.insertDate = insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.last_update
     *
     * @return the value of t_account.last_update
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.last_update
     *
     * @param lastUpdate the value for t_account.last_update
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.note
     *
     * @return the value of t_account.note
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.note
     *
     * @param note the value for t_account.note
     *
     * @mbg.generated Tue Mar 05 14:10:30 CST 2019
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}