server:
  port: 10086
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/account?serverTimezone=GMT
    username: root
    password: 666888
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    mode: HTML
#  mvc:
#    date-format: yyyy-MM-dd hh:mm:ss